"""Added user-homework-problem-image model

Revision ID: 5b328b386482
Revises: b90c4caaadf6
Create Date: 2023-10-25 00:09:21.348911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b328b386482"
down_revision = "b90c4caaadf6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problem-user-homework-image",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("problem_user_homework_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("image_path", sa.String(length=255), nullable=True),
        sa.Column("comment_teacher", sa.String(length=255), nullable=True),
        sa.Column("comment_student", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["problem_user_homework_id"],
            ["problem-user-homework.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("problem-user-homework-image")
    # ### end Alembic commands ###
