"""Changed table name bug corrected

Revision ID: de3c27f5c2be
Revises: 9457d39aebbe
Create Date: 2023-10-25 14:37:40.125940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de3c27f5c2be"
down_revision = "9457d39aebbe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
