"""Added account table

Revision ID: 9fc8addecf06
Revises: 07c71f4389b6
Create Date: 2023-10-23 18:05:15.365128

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9fc8addecf06"
down_revision = "07c71f4389b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles")
    # ### end Alembic commands ###
