"""Added autogenerated id on roles pt3

Revision ID: 7aa2f5ab00ba
Revises: 9e630bb85fb6
Create Date: 2023-10-24 01:36:46.111158

"""

# revision identifiers, used by Alembic.
revision = "7aa2f5ab00ba"
down_revision = "9e630bb85fb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
