"""Added user-homework model

Revision ID: 2632e642dca3
Revises: 57638db5330c
Create Date: 2023-10-24 23:59:39.853214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2632e642dca3"
down_revision = "57638db5330c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "homework-user",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("homework_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["homework_id"],
            ["homework.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("homework-user")
    # ### end Alembic commands ###
