"""Reinit alembic 

Revision ID: e556da2ad11a
Revises: 
Create Date: 2023-12-19 21:07:58.149490

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e556da2ad11a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "class",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "homework",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("dateOfCreation", sa.TIMESTAMP(), nullable=True),
        sa.Column("deadline", sa.TIMESTAMP(), nullable=True),
        sa.Column("maxNumbersOfTasks", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NOT_STARTED", "IN_PROGRESS", "FINISHED", name="homeworkstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("originalImageID", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_images_id"), "images", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMINISTRATOR",
                "PROFESSOR",
                "STUDENT",
                "TA",
                "GUEST",
                name="user_role_enum",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "classHomework",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("class_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("homework_id", sa.UUID(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.id"],
        ),
        sa.ForeignKeyConstraint(
            ["homework_id"],
            ["homework.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_model",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("role_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("surname", sa.String(length=100), nullable=True),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_model_email"), "user_model", ["email"], unique=True)
    op.create_table(
        "homework-user",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("homework_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("note_student", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["homework_id"],
            ["homework.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task-user-homework",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("homework_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("order_number_of_the_task", sa.Integer(), nullable=True),
        sa.Column("commentProfessor", sa.String(length=255), nullable=True),
        sa.Column("commentStudent", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["homework_id"],
            ["homework.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user-class",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("class_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task-user-homework-image",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("task_user_homework_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("image_id", sa.UUID(), nullable=True),
        sa.Column("comment_professor", sa.String(length=255), nullable=True),
        sa.Column("comment_student", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_user_homework_id"],
            ["task-user-homework.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task-user-homework-image")
    op.drop_table("user-class")
    op.drop_table("task-user-homework")
    op.drop_table("homework-user")
    op.drop_index(op.f("ix_user_model_email"), table_name="user_model")
    op.drop_table("user_model")
    op.drop_table("classHomework")
    op.drop_table("roles")
    op.drop_index(op.f("ix_images_id"), table_name="images")
    op.drop_table("images")
    op.drop_table("homework")
    op.drop_table("class")
    # ### end Alembic commands ###
