"""Added autogenerated id on roles revert

Revision ID: 466a1336765f
Revises: 7aa2f5ab00ba
Create Date: 2023-10-24 01:38:46.190490

"""

# revision identifiers, used by Alembic.
revision = "466a1336765f"
down_revision = "7aa2f5ab00ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
