"""fix

Revision ID: f8ba577503f4
Revises: a9649e03b9dc
Create Date: 2023-12-15 14:48:54.198781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8ba577503f4"
down_revision = "a9649e03b9dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("originalImageID", sa.UUID(), nullable=True))
    op.add_column(
        "task-user-homework-image", sa.Column("image_path", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task-user-homework-image", "image_path")
    op.drop_column("images", "originalImageID")
    # ### end Alembic commands ###
