"""a

Revision ID: be1c65f6e08e
Revises: fe47e467978a
Create Date: 2023-12-05 16:55:12.400814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be1c65f6e08e"
down_revision = "fe47e467978a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
