"""Added fk to user on role

Revision ID: b42c93be23ba
Revises: 9fc8addecf06
Create Date: 2023-10-24 00:00:02.068184
"""


# revision identifiers, used by Alembic.
revision = "b42c93be23ba"
down_revision = "9fc8addecf06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
