"""added_img_path_to_upload_img

Revision ID: a9649e03b9dc
Revises: fe47e467978a
Create Date: 2023-12-12 22:05:32.335673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9649e03b9dc"
down_revision = "fe47e467978a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
