"""added column note_student in homework-user table

Revision ID: fe47e467978a
Revises: 67a6a62b144b
Create Date: 2023-12-02 23:12:51.931561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe47e467978a"
down_revision = "67a6a62b144b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "homework-user", sa.Column("note_student", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("homework-user", "note_student")
    # ### end Alembic commands ###
