"""Added autogenerated id on roles pt2

Revision ID: 9e630bb85fb6
Revises: 8a5643f33487
Create Date: 2023-10-24 01:33:27.390710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e630bb85fb6"
down_revision = "8a5643f33487"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
