"""empty message

Revision ID: 67a6a62b144b
Revises: 5ef361f31e8b
Create Date: 2023-11-21 16:06:17.529113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "67a6a62b144b"
down_revision = "5ef361f31e8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_images_id"), "images", ["id"], unique=False)
    op.create_table(
        "task-user-homework",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("homework_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("order_number_of_the_task", sa.Integer(), nullable=True),
        sa.Column("commentProfessor", sa.String(length=255), nullable=True),
        sa.Column("commentStudent", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["homework_id"],
            ["homework.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task-user-homework-image",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("task_user_homework_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("image_id", sa.UUID(), nullable=True),
        sa.Column("comment_professor", sa.String(length=255), nullable=True),
        sa.Column("comment_student", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_user_homework_id"],
            ["task-user-homework.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("problem-user-homework-image")
    op.drop_table("problem-user-homework")
    op.add_column(
        "homework", sa.Column("maxNumbersOfTasks", sa.Integer(), nullable=True)
    )
    op.drop_column("homework", "maxNumbersOfProblems")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "homework",
        sa.Column(
            "maxNumbersOfProblems", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("homework", "maxNumbersOfTasks")
    op.create_table(
        "problem-user-homework",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("homework_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "order_number_of_the_task", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "commentTeacher", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "commentStudent", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["homework_id"],
            ["homework.id"],
            name="problem-user-homework_homework_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_model.id"], name="problem-user-homework_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="problem-user-homework_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "problem-user-homework-image",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "problem_user_homework_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "image_path", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "comment_teacher",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "comment_student",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["problem_user_homework_id"],
            ["problem-user-homework.id"],
            name="problem-user-homework-image_problem_user_homework_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="problem-user-homework-image_pkey"),
    )
    op.drop_table("task-user-homework-image")
    op.drop_table("task-user-homework")
    op.drop_index(op.f("ix_images_id"), table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###
