"""Added autogenerated id on roles

Revision ID: 8a5643f33487
Revises: ae729ba9fb0c
Create Date: 2023-10-24 01:28:02.376218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a5643f33487"
down_revision = "ae729ba9fb0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
