"""test

Revision ID: 83e01dc595a9
Revises: 5b328b386482
Create Date: 2023-10-25 00:17:22.600840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83e01dc595a9"
down_revision = "5b328b386482"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
